# Generated by Django 5.0.3 on 2024-08-14 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number', models.IntegerField()),
                ('marital_status', models.CharField(max_length=100, null=True)),
                ('home_town', models.CharField(max_length=200)),
                ('current_location', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('curent_locations', models.CharField(max_length=100)),
                ('resume', models.ImageField(blank=True, null=True, upload_to='resume/')),
                ('preferred_job_type', models.CharField(max_length=200)),
                ('total_years_of_experince', models.IntegerField()),
                ('availability_to_join', models.CharField(max_length=200, null=True)),
                ('work_parmit_for_USA', models.BooleanField()),
                ('language', models.CharField(max_length=200)),
                ('about', models.CharField(default=True, max_length=400, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='applicant_ids',
            field=models.ManyToManyField(related_name='skills', to='myapp.applicant'),
        ),
    ]
