# Generated by Django 5.0.3 on 2024-08-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_applicant_remove_skill_name_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='department',
            field=models.ManyToManyField(related_name='skills', to='myapp.applicant'),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
