# Generated by Django 5.0.3 on 2024-08-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_skill_department_remove_skill_name_skill_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='department',
            new_name='applicant_ids',
        ),
    ]
