# Generated by Django 5.0.3 on 2024-08-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_department_skill_applicant_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applicant_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
